export type Entry = {
  slug: string;
  title: string;
  summary: string;
  type: "Skill" | "Species" | "Equipment" | "Hazard" | "Concept" | "Track & Sign";
  domain: string;
  level: "Foundation" | "Field Ready" | "Advanced";
  region: string;
  reviewed: string;
  badge: string;
  mark: string;
  tone: "ember" | "lake" | "moss" | "leather" | "pine";
  interactive?: boolean;
  offline?: boolean;
};

export const entries: Entry[] = [
  {
    slug: "building-a-basic-campfire",
    title: "Building a Basic Campfire",
    summary: "The materials, structure, and safety practices behind a small, controlled fire.",
    type: "Skill",
    domain: "Firecraft",
    level: "Foundation",
    region: "North America",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "△",
    tone: "ember",
    interactive: true,
    offline: true,
  },
  {
    slug: "black-bear",
    title: "American Black Bear",
    summary: "Identification, range, behavior, sign, and practical conflict prevention.",
    type: "Species",
    domain: "Wildlife",
    level: "Foundation",
    region: "North America",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "●",
    tone: "pine",
    interactive: true,
    offline: true,
  },
  {
    slug: "baseplate-compass",
    title: "Baseplate Compass",
    summary: "Understand compass anatomy, bearings, declination, and field-ready inspection.",
    type: "Equipment",
    domain: "Navigation",
    level: "Foundation",
    region: "Global",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "✣",
    tone: "lake",
    interactive: true,
    offline: true,
  },
  {
    slug: "hypothermia",
    title: "Hypothermia",
    summary: "Recognize cold stress early and understand when evacuation is required.",
    type: "Hazard",
    domain: "Safety",
    level: "Foundation",
    region: "Global",
    reviewed: "Jul 27, 2026",
    badge: "Medical sources checked",
    mark: "!",
    tone: "lake",
    interactive: true,
    offline: true,
  },
  {
    slug: "white-tailed-deer-track",
    title: "White-tailed Deer Track",
    summary: "A heart-shaped hoof print, gait patterns, habitat clues, and common lookalikes.",
    type: "Track & Sign",
    domain: "Tracking",
    level: "Foundation",
    region: "North America",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "⌁",
    tone: "leather",
    interactive: true,
    offline: true,
  },
  {
    slug: "water-purification",
    title: "Water Purification",
    summary: "Compare boiling, chemical treatment, filtration, and combined approaches.",
    type: "Skill",
    domain: "Water",
    level: "Field Ready",
    region: "Global",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "≈",
    tone: "lake",
    interactive: true,
    offline: true,
  },
  {
    slug: "lightning-safety",
    title: "Lightning Safety",
    summary: "Read changing conditions, reduce exposure, and respond to immediate danger.",
    type: "Hazard",
    domain: "Safety",
    level: "Foundation",
    region: "Global",
    reviewed: "Jul 27, 2026",
    badge: "Official guidance checked",
    mark: "ϟ",
    tone: "leather",
    interactive: true,
    offline: true,
  },
  {
    slug: "fixed-blade-knife",
    title: "Fixed-blade Knife",
    summary: "Anatomy, steel, edge geometry, safe handling, maintenance, and field limitations.",
    type: "Equipment",
    domain: "Tools",
    level: "Field Ready",
    region: "Global",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "╱",
    tone: "moss",
    interactive: true,
  },
  {
    slug: "brook-trout",
    title: "Brook Trout",
    summary: "A cold-water char identified by vermiculation, pale spots, and white fin edges.",
    type: "Species",
    domain: "Fishing",
    level: "Field Ready",
    region: "North America",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "◖",
    tone: "lake",
    interactive: true,
  },
  {
    slug: "contour-lines",
    title: "Reading Contour Lines",
    summary: "Translate close curves and intervals into slope, ridge, valley, and route choices.",
    type: "Concept",
    domain: "Navigation",
    level: "Foundation",
    region: "Global",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "≋",
    tone: "moss",
    interactive: true,
    offline: true,
  },
  {
    slug: "food-storage",
    title: "Food Storage in Bear Country",
    summary: "Keep food and scented items inaccessible using region-appropriate methods.",
    type: "Skill",
    domain: "Camping",
    level: "Foundation",
    region: "North America",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "□",
    tone: "pine",
    interactive: true,
    offline: true,
  },
  {
    slug: "poison-ivy",
    title: "Poison Ivy",
    summary: "Identify variable leaf forms and understand exposure prevention and limitations.",
    type: "Species",
    domain: "Plants",
    level: "Foundation",
    region: "North America",
    reviewed: "Jul 27, 2026",
    badge: "Sources checked",
    mark: "♧",
    tone: "moss",
    interactive: true,
  },
];

export const domains = [
  ["Firecraft", "Combustion, materials, lays, safety, and extinguishing.", "△", "ember"],
  ["Navigation", "Maps, compass, route planning, terrain, GPS, and response.", "✣", "lake"],
  ["Wildlife", "Species, behavior, habitat, safety, ecology, and conservation.", "●", "pine"],
  ["Safety", "Prevention, hazards, first aid, communications, and evacuation.", "+", "leather"],
  ["Tools & Gear", "Anatomy, selection, safe use, maintenance, and repair.", "╱", "moss"],
  ["Water", "Finding, collecting, filtering, treating, and storing water.", "≈", "lake"],
] as const;

export const guides = [
  {
    title: "Your First Camping Trip",
    summary: "A calm, practical route from planning through breaking camp.",
    entries: 9,
    time: "55 min",
    level: "Foundation",
    progress: 9,
  },
  {
    title: "Firecraft Fundamentals",
    summary: "Understand fire before striking a match: safety, materials, structure, and control.",
    entries: 11,
    time: "1 hr 20 min",
    level: "Foundation",
    progress: 5,
  },
  {
    title: "Navigation Basics",
    summary: "Build a dependable mental model of maps, compass, terrain, and being lost.",
    entries: 8,
    time: "1 hr",
    level: "Foundation",
    progress: 7,
  },
];
